version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: knowledge          
    networks:
      - my_network             
    ports:
      - "5432:5432"         
    volumes:
      - ./db_data:/var/lib/postgresql/data   

volumes:
  minio_data:                  
networks:
  my_network:                           